name: Coding Standard With Baseline
on:
  pull_request:
    branches:
      - 2.4-develop
permissions:
  contents: read
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Run Coding Standard Baseline
        uses: Tjitse-E/github-actions/coding-standard-baseline@bugfix/changed-files
        with:
          head_repo: vpodorozh/mageos-magento2
          head_ref: full-integration-tests-workflow
#          head_repo: ${{github.event.pull_request.head.repo.full_name}}
#          head_ref: ${{github.event.pull_request.head.ref}}

