name: Coding Standard With Baseline
on:
  push:
    branches:
      - testing/codingstandard_baseline_integration
  pull_request:
    branches:
      - 2.4-develop
      - testing/codingstandard_baseline_integration

permissions:
  contents: read
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Run Coding Standard Baseline
        uses: mage-os/github-actions/coding-standard-baseline@main

