name: Coding Standard With Baseline
on:
  push:
      branches:
        - test/integration-test-pr-withbaseline-tests
  pull_request:
    branches:
      - 2.4-develop
permissions:
  contents: read
jobs:
  coding-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Run Coding Standard Baseline
        uses: mage-os/github-actions/coding-standard-baseline@main

