name: Run setup:di:compile

on:
  push:
  workflow_dispatch:
    inputs:
      php_version:
        description: 'The PHP version to use'
        required: true
        default: '8.1'
        type: choice
        options:
          - '8.1'
          - '8.2'
      composer_version:
        description: 'The version of composer to use'
        required: true
        default: '2'
        type: choice
        options:
          - '1'
          - '2'

permissions:
  contents: read

jobs:
  setup-di-compile:
    name: Run bin/magento setup:di:compile
    runs-on: ubuntu-latest
    steps:
      - name: Run setup:di:compile
        uses: Tjitse-E/github-actions/setup-di-compile@feat/setup-di-compile-branch-input
        with:
          php_version: ${{ github.event.inputs.php_version }}
          composer_version: ${{ github.event.inputs.composer_version }}
